# Generated by Django 5.2.2 on 2025-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0004_alter_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
