# Generated by Django 5.2.2 on 2025-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0008_alter_task_priority_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('UR', 'Urgent'), ('HI', 'High'), ('ME', 'Medium'), ('LO', 'LOW')], default='ME', max_length=2),
        ),
    ]
