# Generated by Django 5.2.2 on 2025-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'In progress')], default=False),
        ),
    ]
