# Generated by Django 5.2.2 on 2025-06-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0010_alter_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='status',
        ),
    ]
