# Generated by Django 5.2.2 on 2025-06-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0011_rename_is_completed_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority', '-status', 'name')},
        ),
    ]
